<?php	
	$importCategoryTotal = Mage::getSingleton('core/session')->getimportCategoryTotal();
	$importProductsTotal = Mage::getSingleton('core/session')->getimportProductsTotal();	
?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><h1><strong>osCommerce Products/Categories Import </strong></h1></td>
  </tr>
  <tr>
    <td><strong>Step 3. Preparing TMP Tables</strong></td>
  </tr>
  <tr>
    <td><br /><br />
</td>
  </tr>
  <tr>
    <td>We will go to conect to the oscommerce database and read all the products id and categories id and save the information in the tmp tables</td>
  </tr>
  <tr>
    <td><br />
      <strong>Total categories to import:</strong> <?php echo $importCategoryTotal; ?><br />
      <strong>Total products to import:</strong> <?php echo $importProductsTotal; ?></td>
  </tr>
  <tr>
    <td><br />
    <br />
    <br />    <div align="center"><a href="<?php echo $this->getUrl('oscommerceimport')?>">Main Menu</a></div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><div align="center">Powered by <a href="http://www.atwoodz.com/" target="_blank">ezMage</a> - We provide Magento Support 702-485-3332</div></td>
  </tr>
</table>
