<?php	

	$importCategoryTotal = Mage::getSingleton('core/session')->getimportCategoryTotal();

	$importedCategoryTotal = Mage::getSingleton('core/session')->getimportedCategoryTotal();	

?>

<table width="100%" border="0" cellspacing="0" cellpadding="0">

  <tr>

    <td align="center"><h1><strong>osCommerce Products/Categories Import </strong></h1></td>

  </tr>

  <tr>

    <td><strong>Step 4. Import Categories</strong></td>

  </tr>

  <tr>

    <td><br /><br />

</td>

  </tr>

  <tr>

    <td><br />

    <?php if ($importCategoryTotal != $importedCategoryTotal) { ?>

    Click the link below to import the categories<br /><br />

      <a href="<?php echo $this->getUrl('oscommerceimport/index/step41/')?>">Please click to import</a>

    <?php }else{?>  

      Congratulation the categories have been imported <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);  ?>Ezmage/OscommerceImport/check-ok.jpg" />

    <?php }?>      

      <br />

      <br /> 

      <br />

      <strong>Total categories to import:</strong> <?php echo $importCategoryTotal; ?><br />

      <strong>Total categories imported:</strong> <?php echo $importedCategoryTotal; ?></td>

  </tr>

  <tr>

    <td><br />

    <br />

    <br />    <div align="center"><a href="<?php echo $this->getUrl('oscommerceimport')?>">Main Menu</a></div></td>

  </tr>

  <tr>

    <td>&nbsp;</td>

  </tr>

  <tr>

    <td><div align="center">Powered by <a href="http://www.atwoodz.com/" target="_blank">ezMage</a> - We provide Magento Support 702-485-3332</div></td>

  </tr>

</table>

